### ISSUE TITLE
I/O File absent exception

### ISSUE THREAD

**Issue by RafikFarhad** [RafikFarhad/SUST-Online-Judge#6]
Stacktrace: 

2019-02-08 03:15:02,044 server.py    DEBUG    recdata
{"contestId":"0","problemId":"17","subTime":"1549543283","subId":"8440","userId":"1206","lang":"1","judge":0,"freeze":0,"contest_type":"icpc","peAllowed":1,"penaltyPerWa":20}
recdata end
2019-02-08 03:15:02,045 server.py    INFO     New submission received : 8440
2019-02-08 03:15:02,045 operationDispatcher.py DEBUG    json does not contains any special command...
2019-02-08 03:15:02,045 operationDispatcher.py DEBUG    checking if the json is valid
2019-02-08 03:15:02,046 operationDispatcher.py DEBUG    standard
2019-02-08 03:15:02,046 server.py    DEBUG    Standard judge operation
2019-02-08 03:15:02,048 server.py    INFO     Virtually assigned core : [ 0 ] to submission : 8440
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 163, in process_thread
    ui_updater = UIVerdictUpdater(self.judge_host, self.node_port, pdata["subId"])
TypeError: __init__() takes 3 positional arguments but 4 were given

**Comment by RafikFarhad** [comment]
Handled.
Now the error flagged as CE. 
Enough (!) for now.
