### ISSUE TITLE
No proper verdict for missing solution file

### ISSUE THREAD

**Issue by RafikFarhad** [RafikFarhad/SUST-Online-Judge#91]
If the solution file is not present on the file server,
the verdict remains 'COMPILING', should be `Judging Error` or any proper verdict.
Stacktrace:
```
2020-10-01T23:50:15.800 25 sustoj.filebroker.s3_file_server DEBUG    download file to cache: /home/farhad/Desktop/judgeModData/25.c
2020-10-01T23:50:15.819 25 sustoj.root.judge  ERROR    An error occurred (404) when calling the HeadObject operation: Not Found
Traceback (most recent call last):
  File "/home/farhad/playground/JudgeMod/sustoj/root/judge.py", line 64, in grade_submission
    self.compile()
  File "/home/farhad/playground/JudgeMod/sustoj/root/judge.py", line 41, in compile
    self.file_server.get_file(self.submission.src.name, self.submission.src.path,
  File "/home/farhad/playground/JudgeMod/sustoj/filebroker/base_filebroker.py", line 66, in get_file
    self.download_file_to(url, cache_file_path)
  File "/home/farhad/playground/JudgeMod/sustoj/filebroker/s3_file_server.py", line 29, in download_file_to
    self.client.download_file(self.conf['storage_bucket'], url, file_path)
  File "/usr/lib/python3.8/site-packages/boto3-1.14.7-py3.8.egg/boto3/s3/inject.py", line 170, in download_file
    return transfer.download_file(
  File "/usr/lib/python3.8/site-packages/boto3-1.14.7-py3.8.egg/boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/usr/lib/python3.8/site-packages/s3transfer-0.3.3-py3.8.egg/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/usr/lib/python3.8/site-packages/s3transfer-0.3.3-py3.8.egg/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/usr/lib/python3.8/site-packages/s3transfer-0.3.3-py3.8.egg/s3transfer/tasks.py", line 255, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/usr/lib/python3.8/site-packages/s3transfer-0.3.3-py3.8.egg/s3transfer/download.py", line 340, in _submit
    response = client.head_object(
  File "/usr/lib/python3.8/site-packages/botocore-1.17.7-py3.8.egg/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python3.8/site-packages/botocore-1.17.7-py3.8.egg/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
2020-10-01T23:50:15.822 25 sustoj.resource_manager.thread_pool CRITICAL 'str' object has no attribute 'uid'
2020-10-01T23:50:15.822 25 sustoj.resource_manager.thread_pool INFO     Released Thread : [ 25 ] from submission : 25

```

**Comment by talatmursalin** [comment]
resolved in commit acfe828
